include_guard(GLOBAL)

include(CMakeParseArguments)

set(PC_CONF_DIR "${CMAKE_CURRENT_LIST_DIR}")

macro(pc_include_machine_config)
  if(NOT PC_MACHINE_CONFIG_LOADED_THIS_RUN)
    set(_candidates)
    if(DEFINED SYSTEM_LIB_LOADING_FILE)
      list(APPEND _candidates "${SYSTEM_LIB_LOADING_FILE}")
    endif()
    if(DEFINED ENV{SYSTEM_LIB_LOADING_FILE})
      list(APPEND _candidates "$ENV{SYSTEM_LIB_LOADING_FILE}")
    endif()

    list(APPEND _candidates
      "${PC_CONF_DIR}/system_lib_loading.cmake"
    )

    foreach(_candidate IN LISTS _candidates)
      if(_candidate AND EXISTS "${_candidate}")
        message(STATUS "Loading machine config: ${_candidate}")
        include("${_candidate}")
        set(PC_MACHINE_CONFIG_LOADED_THIS_RUN TRUE)
        break()
      endif()
    endforeach()

    if(NOT PC_MACHINE_CONFIG_LOADED_THIS_RUN)
      message(FATAL_ERROR
        "Could not find system_lib_loading.cmake. "
        "Set SYSTEM_LIB_LOADING_FILE or place the file in Parallel-Computing/conf.")
    endif()
  endif()
endmacro()

macro(pc_apply_machine_compilers)
  if(DEFINED PC_MPI_C_COMPILER)
    set(CMAKE_C_COMPILER "${PC_MPI_C_COMPILER}")
    set(CMAKE_C_COMPILER "${PC_MPI_C_COMPILER}" CACHE FILEPATH "MPI C compiler" FORCE)
    set(ENV{CC} "${PC_MPI_C_COMPILER}")
  endif()
  if(DEFINED PC_MPI_CXX_COMPILER)
    set(CMAKE_CXX_COMPILER "${PC_MPI_CXX_COMPILER}")
    set(CMAKE_CXX_COMPILER "${PC_MPI_CXX_COMPILER}" CACHE FILEPATH "MPI CXX compiler" FORCE)
    set(ENV{CXX} "${PC_MPI_CXX_COMPILER}")
  endif()
  if(DEFINED PC_CUDA_COMPILER)
    set(CMAKE_CUDA_COMPILER "${PC_CUDA_COMPILER}")
    set(CMAKE_CUDA_COMPILER "${PC_CUDA_COMPILER}" CACHE FILEPATH "CUDA compiler" FORCE)
  endif()
  if(DEFINED PC_MPI_CXX_COMPILER)
    set(CMAKE_CUDA_HOST_COMPILER "${PC_MPI_CXX_COMPILER}")
    set(CMAKE_CUDA_HOST_COMPILER "${PC_MPI_CXX_COMPILER}" CACHE FILEPATH "CUDA host compiler" FORCE)
  endif()
  if(DEFINED PC_CUDA_ROOT)
    set(CUDAToolkit_ROOT "${PC_CUDA_ROOT}")
    set(CUDA_TOOLKIT_ROOT_DIR "${PC_CUDA_ROOT}")
    set(CUDAToolkit_ROOT "${PC_CUDA_ROOT}" CACHE PATH "CUDA toolkit root" FORCE)
    set(CUDA_TOOLKIT_ROOT_DIR "${PC_CUDA_ROOT}" CACHE PATH "CUDA toolkit root" FORCE)
  endif()
endmacro()

function(pc_set_default_build_flags)
  if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release CACHE STRING "Build type" FORCE)
  endif()

  if(NOT DEFINED CMAKE_CXX_STANDARD)
    set(CMAKE_CXX_STANDARD 11 PARENT_SCOPE)
  endif()
  set(CMAKE_CXX_STANDARD_REQUIRED TRUE PARENT_SCOPE)

  if(CMAKE_BUILD_TYPE MATCHES "Release")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wall" PARENT_SCOPE)
  else()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0 -g -Wall -DENABLE_TEST" PARENT_SCOPE)
  endif()

  if(DEFINED PC_VERBOSE_MAKEFILE)
    set(CMAKE_VERBOSE_MAKEFILE "${PC_VERBOSE_MAKEFILE}" PARENT_SCOPE)
  endif()
endfunction()

macro(pc_setup_common_dependencies)
  set(options USE_OPENMP USE_MPI USE_PETSC USE_SLEPC USE_CUDA)
  set(one_value_args MODULE_DIR)
  cmake_parse_arguments(PC "${options}" "${one_value_args}" "" ${ARGN})

  include_directories("${PC_CONF_DIR}")

  set(_pc_mpi_include_dirs)
  if(DEFINED PC_MPI_INCLUDE_DIRS)
    list(APPEND _pc_mpi_include_dirs ${PC_MPI_INCLUDE_DIRS})
  endif()

  if(PC_MODULE_DIR)
    list(APPEND CMAKE_MODULE_PATH "${PC_MODULE_DIR}")
  endif()

  if(DEFINED PC_EXTRA_CMAKE_MODULE_PATH)
    list(APPEND CMAKE_MODULE_PATH ${PC_EXTRA_CMAKE_MODULE_PATH})
  endif()

  if(DEFINED PC_EIGEN3_INCLUDE_DIR)
    set(EIGEN3_INCLUDE_DIR "${PC_EIGEN3_INCLUDE_DIR}")
    include_directories("${PC_EIGEN3_INCLUDE_DIR}")
  endif()

  if(PC_USE_OPENMP)
    find_package(OpenMP REQUIRED)
    if(DEFINED PC_OPENMP_CXX_INCLUDE_DIR)
      include_directories("${PC_OPENMP_CXX_INCLUDE_DIR}")
    endif()
  endif()

  if(PC_USE_MPI)
    find_package(MPI REQUIRED)
    if(DEFINED MPI_C_INCLUDE_DIRS)
      list(APPEND _pc_mpi_include_dirs ${MPI_C_INCLUDE_DIRS})
    endif()
    if(DEFINED MPI_CXX_INCLUDE_DIRS)
      list(APPEND _pc_mpi_include_dirs ${MPI_CXX_INCLUDE_DIRS})
    endif()
    if(DEFINED MPI_C_COMPILER_INCLUDE_DIRS)
      list(APPEND _pc_mpi_include_dirs ${MPI_C_COMPILER_INCLUDE_DIRS})
    endif()
    if(DEFINED MPI_CXX_COMPILER_INCLUDE_DIRS)
      list(APPEND _pc_mpi_include_dirs ${MPI_CXX_COMPILER_INCLUDE_DIRS})
    endif()
  endif()

  if(_pc_mpi_include_dirs)
    list(REMOVE_DUPLICATES _pc_mpi_include_dirs)
    include_directories(${_pc_mpi_include_dirs})
    set(MPI_C_INCLUDE_PATH "${_pc_mpi_include_dirs}")
    set(MPI_C_INCLUDE_DIRS "${_pc_mpi_include_dirs}")
    set(MPI_CXX_INCLUDE_DIRS "${_pc_mpi_include_dirs}")
  endif()
  if(DEFINED PC_MPI_LIBRARIES)
    set(MPI_C_LIBRARIES "${PC_MPI_LIBRARIES}")
    set(MPI_CXX_LIBRARIES "${PC_MPI_LIBRARIES}")
  endif()

  if(PC_USE_PETSC)
    if(DEFINED PC_PETSC_DIR)
      set(PETSC_DIR "${PC_PETSC_DIR}")
      set(PETSC_DIR "${PC_PETSC_DIR}" CACHE PATH "PETSc root" FORCE)
      set(ENV{PETSC_DIR} "${PC_PETSC_DIR}")
    endif()
    if(DEFINED PC_PETSC_ARCH)
      set(PETSC_ARCH "${PC_PETSC_ARCH}")
      set(PETSC_ARCH "${PC_PETSC_ARCH}" CACHE STRING "PETSc arch" FORCE)
      set(ENV{PETSC_ARCH} "${PC_PETSC_ARCH}")
    endif()
    find_package(PETSc REQUIRED)
    include_directories(${PETSC_INC})
  endif()

  if(PC_USE_SLEPC)
    if(DEFINED PC_SLEPC_DIR)
      set(SLEPC_DIR "${PC_SLEPC_DIR}")
      set(SLEPC_DIR "${PC_SLEPC_DIR}" CACHE PATH "SLEPc root" FORCE)
      set(ENV{SLEPC_DIR} "${PC_SLEPC_DIR}")
    endif()
    find_package(SLEPc REQUIRED)
    include_directories(${SLEPC_INC})
  endif()

  if(PC_USE_CUDA)
    find_package(CUDAToolkit REQUIRED)
    include_directories(${CUDAToolkit_INCLUDE_DIRS})
    set(CUDA_INC "${CUDAToolkit_INCLUDE_DIRS}")
  endif()
endmacro()

function(pc_enable_openmp_for_targets)
  foreach(_target IN LISTS ARGN)
    if(TARGET "${_target}" AND TARGET OpenMP::OpenMP_CXX)
      target_link_libraries("${_target}" OpenMP::OpenMP_CXX)
      target_compile_definitions("${_target}" PRIVATE USE_OPENMP)
    endif()
  endforeach()
endfunction()

function(pc_configure_cuda_targets)
  foreach(_target IN LISTS ARGN)
    if(TARGET "${_target}")
      set_target_properties("${_target}" PROPERTIES
        CUDA_STANDARD 11
        CUDA_STANDARD_REQUIRED YES
        CUDA_SEPARABLE_COMPILATION ON
      )
      if(DEFINED PC_CUDA_ARCHITECTURES)
        set_property(TARGET "${_target}" PROPERTY CUDA_ARCHITECTURES "${PC_CUDA_ARCHITECTURES}")
      endif()
    endif()
  endforeach()
endfunction()
